spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://192.168.0.105/sell?characterEncoding=utf-8&useSSL=false
  jpa:
    showname: true
  jackson:
    default-property-inclusion: non_null
server:
  context-path: /sell
